---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart alloy
  ansible.builtin.systemd:
    name: alloy
    state: restarted
    daemon_reload: true
  listen: "Restart alloy"
